### ISSUE TITLE
Update lesson to demo following new pattern for using meta tags

### ISSUE THREAD

**Issue by heratyian** [DPI-WE/search-engine-optimization#3]
https://github.com/DPI-WE/readit-2024-5-1-sdf/pull/40

I think it's simpler to use a meta_tags partial view and remove the MetaTagService and deep_merge.

Any @DPI-WE/technical-associates want to give this a try?

**Comment by armstrca** [comment]
Can you give me/us permissions for this repo? Can't make a branch/PR
